name: Gerar Build Android Merenda

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Ativando robô Android
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixando o Código
        uses: actions/checkout@v4

      - name: Configurando o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalando o Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Configurar Projeto e Corrigir Biblioteca
        working-directory: mobile_app
        run: |
          # 1. Recriar estrutura Android/iOS
          flutter create . --platforms=android,ios
          flutter pub get
          
          # 2. Localizar arquivos internos
          MANIFEST_PATH=$(find android -name "AndroidManifest.xml" | grep "main" | head -n 1)
          
          # 3. PATROCÍNIO: Corrigir o erro de ambiguidade 'bigLargeIcon' direto no fonte da biblioteca (Hack Necessário)
          # Isso evita ter que subir a versão e quebrar o build com desugaring
          LIB_PATH=$(find /home/runner/.pub-cache/hosted/pub.dev -name "FlutterLocalNotificationsPlugin.java" | grep "flutter_local_notifications" | head -n 1)
          echo "Path da lib encontrado: $LIB_PATH"
          if [ -n "$LIB_PATH" ]; then
            sed -i 's/bigLargeIcon(null)/bigLargeIcon((Bitmap)null)/g' "$LIB_PATH"
            echo "Correção de ambiguidade aplicada com sucesso no fonte da biblioteca!"
          fi
          
          # 4. Injetar URL Scheme no AndroidManifest
          if [ -n "$MANIFEST_PATH" ]; then
            perl -i -pe 's/<\/activity>/  <intent-filter>\n                <action android:name="android.intent.action.VIEW" \/>\n                <category android:name="android.intent.category.DEFAULT" \/>\n                <category android:name="android.intent.category.BROWSABLE" \/>\n                <data android:scheme="msauth.com.rango.fatec" \/>\n            <\/intent-filter>\n        <\/activity>/g' "$MANIFEST_PATH"
          fi

      - name: Gerando Ícone do App
        working-directory: mobile_app
        run: dart run flutter_launcher_icons

      - name: Construindo o APK Oficial
        working-directory: mobile_app
        run: flutter build apk --release --no-tree-shake-icons

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: merenda-fatec-android
          path: "**/build/app/outputs/flutter-apk/app-release.apk"
