name: Gerar Build iOS Merenda

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Ativando robô iOS
    runs-on: macos-latest
    
    steps:
      - name: Baixando o Código
        uses: actions/checkout@v4

      - name: Instalando o Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Forçar Criação do Ambiente iOS
        run: |
          [ -d "mobile_app" ] && cd mobile_app || echo "Usando raiz"
          flutter create . --platforms=ios --overwrite
          flutter pub get

      - name: Construindo o App iOS (Simulador)
        run: |
          [ -d "mobile_app" ] && cd mobile_app || echo "Usando raiz"
          flutter build ios --simulator --no-tree-shake-icons

      - name: Disponibilizar App para Download
        uses: actions/upload-artifact@v4
        with:
          name: merenda-fatec-ios
          path: "**/build/ios/iphonesimulator/Runner.app"
